### ISSUE TITLE
Missing support for some Spark 3.0 commands

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#259] opened 2021-06-22 08:40 UTC
`org.apache.spark.sql.catalyst.plans.logical.CreateTableAsSelect` is missing, and maybe something else as well.

See https://github.com/AbsaOSS/spline-spark-agent/issues/256#issuecomment-865420765

**Comment by cerveada** [comment] 2021-06-28 08:51
Duplicate of #191

**Closed as completed** 2021-06-28 09:28 UTC
Labels: bug, duplicate, dependency: Spark 3.0+
