### ISSUE TITLE
Executions missing for Delta vs Parquet

### ISSUE THREAD

**Issue by mfrictionless** [AbsaOSS/spline-spark-agent#256] opened 2021-06-18 00:52 UTC
Hey Spline Team,

We're starting to test the Spline bundle on our Databricks clusters where we are defaulting our storage to Delta.  I've run through a test script that creates tables and inserts some data with the following bundles:

- za.co.absa.spline.agent.spark:spark-3.0-spline-agent-bundle_2.12:0.6.0 (DBR 7.6)
- za.co.absa.spline.agent.spark:spark-3.1-spline-agent-bundle_2.12:0.6.1 (DBR 8.3)

Here's the output when the table is created with **PARQUET**

![Screen Shot 2021-06-17 at 5 46 25 PM](https://user-images.githubusercontent.com/62860754/122489232-06230580-cf94-11eb-9cf4-e4f0c9afa77c.png)

Running this same script with **DELTA** there's no output.  

Let me know what else I can provide to help debug this.  I'm trying to figure out if this is a Spline issue or Databricks issue.

Thank you,

M

**Comment by wajda** [comment] 2021-06-18 15:34
The problem is most likely in between Databricks and Spline. 
Spline supports delta, but Databricks uses their own slightly modified Spark runtime with certain internals different from the open-source Spark distribution. Enable DEBUG log level and look for the phrase "XYZ was not recognized as a write-command". If there is such message, enable TRACE logging, find the object dump JSON (it should be printed right after the "was not recognized" message), and send it to us. We'll see what can be done.

**Comment by mfrictionless** [comment] 2021-06-18 19:00
Debug output:

`21/06/18 18:04:47 DEBUG LineageHarvester: Harvesting lineage from class org.apache.spark.sql.execution.command.DescribeTableCommand
21/06/18 18:04:47 DEBUG LineageHarvester: class org.apache.spark.sql.execution.command.DescribeTableCommand was not recognized as a write-command. Skipping.`

Trace Logs attached:

[trace-log-1.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6678861/trace-log-1.txt)
[trace-log-2.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6678864/trace-log-2.txt)
[trace-log-3.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6678870/trace-log-3.txt)
[trace-log-4.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6678871/trace-log-4.txt)
[trace-log-5.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6678873/trace-log-5.txt)

Happy to provide more information/logs on request.

**Comment by wajda** [comment] 2021-06-21 08:29
Could you share a test Spark code that reproduces this behavior please?

I don't see any Delta related commands in the logs, but I do see some traces of commands that aren't expected to be there, like, for instance, `LocalRelation` or `Project` nodes appeared in a place where some write commands should be. Having a source code of the Spark job would greatly help to understand what's happening. Thanks.

**Comment by mfrictionless** [comment] 2021-06-21 23:50
I've attached the code and a part of the trace for a more concise example.

[spline-test-delta-trace.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6690049/spline-test-delta-trace.txt)
[log4j-active.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6690051/log4j-active.txt)

<img width="416" alt="Screen Shot 2021-06-21 at 4 51 57 PM" src="https://user-images.githubusercontent.com/62860754/122841882-1519f880-d2b1-11eb-91b6-928d42dfdf0c.png">

**Comment by wajda** [comment] 2021-06-22 08:37
`org.apache.spark.sql.catalyst.plans.logical.CreateTableAsSelect`
Looks like that class was added in Spark 3, and we missed it. We'll fix it shortly. Thanks for report.

**Comment by mfrictionless** [comment] 2021-06-25 02:59
Following up on this,

I think you were correct in your original assessment of this being related to Delta in Databricks.  The attached test code works perfectly with Parquet tables.

[spline-test-delta-tables.ipynb.txt](https://github.com/AbsaOSS/spline-spark-agent/files/6713235/spline-test-delta-tables.ipynb.txt)


21/06/25 02:49:09 DEBUG LineageHarvester: Harvesting lineage from class org.apache.spark.sql.catalyst.plans.logical.AppendData
21/06/25 02:49:09 DEBUG LineageHarvester: class org.apache.spark.sql.catalyst.plans.logical.AppendData was not recognized as a write-command. Skipping.

21/06/25 02:49:09 ERROR SplineQueryExecutionListener: Unexpected error occurred during lineage processing for application: Databricks Shell #local-1624589026260
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class InterfaceAudience

**Comment by mfrictionless** [comment] 2021-07-13 01:14
This is likely a separate issue but I wanted to raise on this thread because it applied to Delta file support.

Versions tested

- 0.6.1 
- Bundle spark-2.4-spline-agent-bundle_2.11
- Databricks DBR 6.4 

In this scenario lineage is generated but is missing table identifier elements from operation output that I get with Parquet in the same scenario.

With Parquet I get:

```json
"table":{"identifier":{"table":"test_set01_order_item","database":"playground"}}
```

With Delta i get nothing..

**Comment by cerveada** [comment] 2021-07-27 08:33
This should be fixed by #191

**Comment by mfrictionless** [comment] 2021-07-27 14:45
Thanks Adam,

Happy to test this.  I don't have the tools to build this locally right now but if there's a test build available in JAR format for the agent I'm happy to get a head start looking at it.

Cheers,

MIchael

**Comment by cerveada** [comment] 2021-07-28 07:21
I build it for you.

[spark-3.0-spline-agent-bundle_2.12-0.6.2-SNAPSHOT.zip](https://github.com/AbsaOSS/spline-spark-agent/files/6891052/spark-3.0-spline-agent-bundle_2.12-0.6.2-SNAPSHOT.zip)

[spark-3.1-spline-agent-bundle_2.12-0.6.2-SNAPSHOT.zip](https://github.com/AbsaOSS/spline-spark-agent/files/6891067/spark-3.1-spline-agent-bundle_2.12-0.6.2-SNAPSHOT.zip)

Please rename *.zip to *.jar. GitHub doesn't let me upload jars for some reason.

**Comment by wajda** [comment] 2021-08-02 09:15
@mfrictionless Can we close this one?

**Comment by wajda** [comment] 2021-08-05 15:31
I'm closing the ticker assuming it is fixed. Please feel free to reopen it if the issue repeats.

**Closed as completed by wajda** 2021-08-05 15:31 UTC
Labels: bug, dependency: Spark 3.0+

**Comment by mfrictionless** [comment] 2021-08-11 01:40
Starting testing this week.  I'll be able to tell you by EOW.

**Comment by mfrictionless** [comment] 2021-08-19 02:22
Using the Spark 3.0 bundle you provided in the thread.

Catalog: AWS Glue
Databricks Runtime: 7.3
Spark: 3.0.1
Scala: 2.1.2

```scala

%scala
// insert sample data into a parquet/delta table
val df = spark.sql("INSERT INTO playground.test_set02_customer VALUES ('a925eaf2-e342-497b-85fb-773e81bf57f5','Michael Fline','test@test1.test','Santa Monica','CA','USA',1)")
// print execution plans
println(df.queryExecution.executedPlan)
```

Plan:

```
AppendDataExecV1 DeltaTableV2(org.apache.spark.sql.SparkSession@a691a14,s3://central-data-warehouse-prod/playground/test_set02_customer,Some(CatalogTable(
Database: playground
Table: test_set02_customer
Owner: root
Created Time: Thu Aug 19 01:50:08 UTC 2021
Last Access: UNKNOWN
Created By: Spark 3.0.1
Type: MANAGED
Provider: delta
Location: s3://central-data-warehouse-prod/playground/test_set02_customer
Serde Library: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
InputFormat: org.apache.hadoop.mapred.SequenceFileInputFormat
OutputFormat: org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat
Partition Provider: Catalog)),Some(playground.test_set02_customer),None), [], LocalRelation [id#73, name#74, email#75, city#76, state#77, country#78, catagory#79]

df: org.apache.spark.sql.DataFrame = []
```

Results:

```
21/08/19 02:06:38 DEBUG LineageHarvester: Harvesting lineage from class org.apache.spark.sql.catalyst.plans.logical.AppendData
21/08/19 02:06:38 DEBUG LineageHarvester: class org.apache.spark.sql.catalyst.plans.logical.AppendData was not recognized as a write-command. Skipping.
..
21/08/19 02:14:11 ERROR SplineQueryExecutionListener: Unexpected error occurred during lineage processing for application: Databricks Shell #local-1629339163298
java.lang.AssertionError: assertion failed: no symbol could be loaded from interface org.apache.hadoop.classification.InterfaceAudience$Public in class InterfaceAudience with name Public and classloader sun.misc.Launcher$AppClassLoader@28f67ac7
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1061)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:130)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:50)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:46)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:128)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy.<init>(JavaMirrors.scala:196)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:195)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:195)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$copyAnnotations(JavaMirrors.scala:717)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.load(JavaMirrors.scala:772)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.completeTypeParams$1(SynchronizedSymbols.scala:175)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$typeParams$1(SynchronizedSymbols.scala:180)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.typeParams(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.typeParams$(SynchronizedSymbols.scala:165)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.typeParams(SynchronizedSymbols.scala:203)
	at scala.reflect.internal.Types$NoArgsTypeRef.typeParams(Types.scala:1892)
	at scala.reflect.internal.Types$NoArgsTypeRef.isHigherKinded(Types.scala:1891)
	at scala.reflect.internal.transform.UnCurry.scala$reflect$internal$transform$UnCurry$$expandAlias(UnCurry.scala:41)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:45)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:43)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:65)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:138)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:65)
	at scala.reflect.internal.transform.UnCurry.transformInfo(UnCurry.scala:171)
	at scala.reflect.internal.transform.UnCurry.transformInfo$(UnCurry.scala:165)
	at scala.reflect.internal.transform.Transforms$$anon$1.transformInfo(Transforms.scala:38)
	at scala.reflect.internal.transform.Transforms.transformedType(Transforms.scala:49)
	at scala.reflect.internal.transform.Transforms.transformedType$(Transforms.scala:46)
	at scala.reflect.internal.SymbolTable.transformedType(SymbolTable.scala:28)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$methodToJava$1(JavaMirrors.scala:1324)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toJava$1(TwoWayCaches.scala:61)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toJava(TwoWayCaches.scala:57)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.methodToJava(JavaMirrors.scala:1322)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jmeth$lzycompute(JavaMirrors.scala:365)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jmeth(JavaMirrors.scala:365)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror0.jinvokeraw(JavaMirrors.scala:397)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvoke(JavaMirrors.scala:373)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror.apply(JavaMirrors.scala:389)
	at za.co.absa.commons.reflect.ReflectionUtils$.$anonfun$extractFieldValue$4(ReflectionUtils.scala:144)
	at scala.Option.map(Option.scala:230)
	at za.co.absa.commons.reflect.ReflectionUtils$.reflectClass$1(ReflectionUtils.scala:142)
	at za.co.absa.commons.reflect.ReflectionUtils$.reflectClassHierarchy$1(ReflectionUtils.scala:113)
	at za.co.absa.commons.reflect.ReflectionUtils$.extractFieldValue(ReflectionUtils.scala:170)
	at za.co.absa.commons.reflect.ReflectionUtils$.extractFieldValue(ReflectionUtils.scala:185)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.$anonfun$objectToStringRec$3(ObjectStructureDumper.scala:74)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.objectToStringRec(ObjectStructureDumper.scala:73)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.dump(ObjectStructureDumper.scala:32)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$7(LineageHarvester.scala:78)
	at org.apache.spark.internal.Logging.logTrace(Logging.scala:65)
	at org.apache.spark.internal.Logging.logTrace$(Logging.scala:64)
	at za.co.absa.spline.harvester.LineageHarvester.logTrace(LineageHarvester.scala:45)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:78)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:86)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1523)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)

```

**Comment by wajda** [comment] 2021-08-19 09:20
This one is important
```
21/08/19 02:06:38 DEBUG LineageHarvester: class org.apache.spark.sql.catalyst.plans.logical.AppendData was not recognized as a write-command. Skipping.
```
The other error is mostly a noise in this case. I've created a ticket for that - #285

**Comment by wajda** [comment] 2021-08-19 09:29
filed a separate ticket

**Comment by mfrictionless** [comment] 2021-08-19 18:56
For some good news this command is working with the above configuration:

```python
from pyspark.sql.types import *

data = [['a925eaf2-e342-497b-85fb-773e81bf57f5']]
schema = StructType([StructField('id',StringType(),True)])
df = spark.createDataFrame(data,schema)

df.write.format("delta").mode("overwrite").save("s3://central-data-warehouse-prod/playground/test_set02_data")
```

21/08/19 18:50:42 DEBUG LineageHarvester: Harvesting lineage from class org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand
