### ISSUE TITLE
Lineage not showing for overwrite mode for delta table

### ISSUE THREAD

**Issue by mohitgarg4628** [AbsaOSS/spline-spark-agent#507] opened 2022-10-07 05:12 UTC
## Describe the bug
We are trying to capture lineage using spline using overwrite mode. 
Data format is delta. 
We are running our workflow on databricks. When we are using mode as append, we are able to capture lineage

## Versions
Spark Version: 3.2
Spline Version: spark-3.2-spline-agent-bundle_2.12:0.7.11

Could you please help me for the same

**Comment by cerveada** [comment] 2022-10-07 06:37
What code do you use to write (overwrite) the data to delta? I mean the one that is not triggering a lineage generation.

**Comment by mohitgarg4628** [comment] 2022-10-07 06:56
```scala
 dataframe.write.format("delta")
        .mode("overwrite")
        .saveAsTable("rtas1")
```

**Comment by cerveada** [comment] 2022-10-07 07:28
ok, since databricks doesn't provide the source code we can't just debug it, but it should be possible get what we need from the logs.

Please set the logger level for evrything under `za.co.absa.spline` to `TRACE`.
Then run the overwrite and upload the log file here.

There should be message containing:
`was not recognized as a write-command. Skipping.` or  `Write extraction failed for:`

**Comment by mohitgarg4628** [comment] 2022-10-07 07:30
We are getting following error
```
22/10/07 07:21:50 WARN LineageHarvester: Write extraction failed for: class org.apache.spark.sql.catalyst.plans.logical.ReplaceTableAsSelect
java.lang.NoSuchFieldException: org.apache.spark.sql.catalyst.plans.logical.ReplaceTableAsSelect.catalog
	at za.co.absa.commons.reflect.FieldValueExtractor.$anonfun$extract$2(FieldValueExtractor.scala:39)
	at scala.Option.getOrElse(Option.scala:189)
```

**Comment by cerveada** [comment] 2022-10-07 07:32
ok, but we need the full trace log, there should be `OBJECT DUMP BEGIN` and the structure of the object logged.

**Comment by mohitgarg4628** [comment] 2022-10-07 07:36
```
****************************** OBJECT DUMP BEGIN ******************************
class org.apache.spark.sql.catalyst.plans.logical.ReplaceTableAsSelect
  resolved: boolean = true
  name: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan 
    catalog: org.apache.spark.sql.connector.catalog.TableCatalog 
    ident: org.apache.spark.sql.connector.catalog.Identifier 
      namespace: [Ljava.lang.String; 
      name: java.lang.String = rtas1
  partitioning: scala.collection.Seq = List()
  query: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan 
    resolved: boolean = true
    validConstraints: org.apache.spark.sql.catalyst.expressions.ExpressionSet = Set(isnotnull(val#839))
    projectList: scala.collection.Seq = List(_1#833 AS id#838, _2#834 AS val#839)
    nodePatterns: scala.collection.Seq = List(PROJECT)
    bitmap$0: byte = 3
  tableSpec: org.apache.spark.sql.catalyst.plans.logical.TableSpec 
    properties: scala.collection.immutable.Map = Map()
    provider: scala.Option Some
      x: java.lang.String = delta
    options: scala.collection.immutable.Map = Map()
    location: scala.Option = None
    comment: scala.Option = None
    serde: scala.Option = None
    external: boolean = false
    constraints: scala.collection.immutable.Set = Set()
  writeOptions: scala.collection.immutable.Map = Map()
  orCreate: boolean = true
  output: scala.collection.Seq = List(num_affected_rows#846L, num_inserted_rows#847L)
  nodePatterns: scala.collection.Seq = List(COMMAND)
  bitmap$0: boolean = true
****************************** OBJECT DUMP END   ******************************
```

**Comment by cerveada** [comment] 2022-10-07 08:05
The catalog is there, so I don't see what could cause the issue. Can you send the whole log? Maybe there will be something that will tell me more.

**Comment by mohitgarg4628** [comment] 2022-10-07 09:23
This issue is similar to https://github.com/AbsaOSS/spline-spark-agent/issues/487

**Comment by juliuszsompolski** [comment] 2022-10-07 12:21
Spark 3.3 does not have a "catalog" field in ReplaceTableAsSelect. It was removed in https://github.com/apache/spark/pull/34754/files#diff-594addaa7ed3dd43fd0dad5fa81ade5ec2e570adf7c982c0570e3358a08a8e0aL277
Since Spline Agent was reaching via reflection to internal Spark fields, it needs to find a new way to get this catalog...
Unfortunately, I don't have context on what does Spline need it for, and where else it could grab it.

**Comment by cerveada** [comment] 2022-10-07 12:48
@juliuszsompolski you are right, but @mohitgarg4628 said they are using Spark 3.2 So that might be other issue.

**Comment by cerveada** [comment] 2022-10-07 12:54
> This issue is similar to #487

Indeed. But your OBJECT DUMP is different. Is it possible that it is missing indentation? 

indentation is important in this case. As I wrote several times already full log would be useful in this case.

**Comment by juliuszsompolski** [comment] 2022-10-07 13:05
@cerveada I just checked that Databricks Runtime 10.x also has this change, even though it's based on Spark 3.2.
Databricks Runtime interfaces that are not Spark public APIs sometimes differ from Apache Spark's.

**Comment by mohitgarg4628** [comment] 2022-10-10 05:57
Hi @cerveada 
Can you please tell me, if issue is fixed or not?
If yes, how can I get latest maven dependency.
Thanks

**Comment by wajda** [comment] 2022-10-10 08:25
@mohitgarg4628 it's still being investigated. The issue is related to the closed source Databricks runtime, so fixing it is a pure trial and error approach.

**Comment by cerveada** [comment] 2022-10-10 08:38
@mohitgarg4628 could you please download the following jar and try if the issues is fixed for you?

https://teamcity.jetbrains.com/repository/download/OpenSourceProjects_AbsaOSS_SplineAgentSpark_PullRequestsSpark32scala212/3967771:id/bundle-3.2/target/spark-3.2-spline-agent-bundle_2.12-0.7.12-SNAPSHOT.jar

Just press log as guest and it should download.

**Comment by mohitgarg4628** [comment] 2022-10-17 05:26
sure @cerveada . I have already taken a PR and build code on local machine. It was working fine. But when I tried with unity catalog, was getting error for the same.

I need to check with all use cases and will let you know.

Thanks for your overall support

**Comment by cerveada** [comment] 2022-10-26 08:50
ok, seems like the original issue is fixed via #508, and there are new tickets for other issues (#517, #518). So I am closing this ticket.

**Closed as completed by cerveada** 2022-10-26 08:50 UTC
Labels: bug, investigating

**Comment by zacayd** [comment] 2024-01-09 07:50
@cerveada @mohitgarg4628  does spline support cluster of Unity Catalog?
i have an error - attached the log file
[log4j-active123.txt](https://github.com/AbsaOSS/spline-spark-agent/files/13870589/log4j-active123.txt)

**Comment by cerveada** [comment] 2024-01-09 15:54
Support for unity catalog #518 is not implemented yet.

**Comment by zacayd** [comment] 2024-01-09 16:14
also cluster that uses unity catalog?
