### ISSUE TITLE
The project cannot compile properly

### ISSUE THREAD

**Issue by asaiai18894** [AbsaOSS/spline-spark-agent#421] opened 2022-04-08 06:35 UTC
Various packages are missing
Unable to compile from project

<img width="608" alt="image" src="https://user-images.githubusercontent.com/59914524/162378124-75c58aeb-1aa5-4823-8fb7-265fe0fe83f2.png">

**Comment by cerveada** [comment] 2022-04-08 06:44
Please run `mvn clean compile` and let us know if it is successful.

Also, please write which branch you are on and which Java version is used for compilation.

**Comment by asaiai18894** [comment] 2022-04-08 07:03
mvn clean compile 
The result ：Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.5.0:compile (scala-compile) on project agent-core_2.11: Execution scala-compile of goal net.alchim31.maven:scala-maven-plugin:4.5.0:compile failed.

branch is develop
Java version  : 8

**Comment by cerveada** [comment] 2022-04-08 07:55
That is the result, but there must be another error in the Maven log, that caused the compilation to fail. Please send the error or maybe the whole Maven log.

**Comment by asaiai18894** [comment] 2022-04-08 08:04
> That is the result, but there must be another error in the Maven log, that caused the compilation to fail. Please send the error or maybe the whole Maven log.

by making the implicit value `scala.language.reflectiveCalls` visible.
This can be achieved by adding the import clause `import scala.language.reflectiveCalls`
or by setting the compiler option `-language:reflectiveCalls`.
See the Scaladoc for value `scala.language.reflectiveCalls` for a discussion
why the feature should be explicitly enabled.
```
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:19: object IdGenerator is not a member of package za.co.absa.spline.harvester
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:25: not found: type UUIDGeneratorFactory
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:26: not found: type IdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:27: not found: type IdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:27: not found: type SequentialIdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:28: not found: type IdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:28: not found: type SequentialIdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:29: not found: type IdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:29: not found: type SequentialIdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:30: not found: type IdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:31: not found: type ComposableIdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:32: not found: type SequentialIdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:33: not found: type UUID5IdGenerator
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:33: not found: value UUIDNamespace
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/LineageHarvester.scala:97: type mismatch;
 found   : Option[Seq[za.co.absa.spline.producer.model.v1_1.FunctionalExpression]]
 required: Seq[za.co.absa.spline.producer.service.model.v1_1.FunctionalExpression]
[ERROR] /Users/liuyucheng/Project/spline/spline-spark-agent-release-0.7.3/core/src/main/scala/za/co/absa/spline/harvester/LineageHarvester.scala:96: type mismatch;
 found   : Option[Seq[za.co.absa.spline.producer.model.v1_1.Literal]]
 required: Seq[za.co.absa.spline.producer.service.model.v1_1.Literal]
```

**Comment by cerveada** [comment] 2022-04-08 08:34
This looks like a duplicate of #410. Please update your branch to the latest commit, where it should be fixed.

**Comment by asaiai18894** [comment] 2022-04-08 08:47
> This looks like a duplicate of #410. Please update your branch to the latest commit, where it should be fixed.

Pulled 0.7.6 again
```
[INFO] 
[INFO] ------------< za.co.absa.spline.agent.spark:examples_2.11 >-------------
[INFO] Building examples_2.11 0.7.6                                       [3/4]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ examples_2.11 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- scala-maven-plugin:4.5.0:add-source (scala-compile) @ examples_2.11 ---
[INFO] Add Source directory: /Users/liuyucheng/Project/spline-spark-agent-release-0.7.6/examples/src/main/scala
[INFO] Add Test Source directory: /Users/liuyucheng/Project/spline-spark-agent-release-0.7.6/examples/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:4.5.0:compile (scala-compile) @ examples_2.11 ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /Users/liuyucheng/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.11-1.5.1-bin_2.11.12__52.0-1.5.1_20210425T221145.jar
[INFO] compiling 20 Scala sources and 1 Java source to /Users/liuyucheng/Project/spline-spark-agent-release-0.7.6/examples/target/classes ...
[WARNING] javac exited with exit code -1
[ERROR] ## Exception when compiling 21 sources to /Users/liuyucheng/Project/spline-spark-agent-release-0.7.6/examples/target/classes
java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/javac" (in directory "/Users/liuyucheng/Project/spline-spark-agent-release-0.7.6"): error=2, No such file or directory
java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:85)
scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:119)
scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:205)
scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
sbt.internal.inc.javac.JavacLogger.buffer(JavacProcessLogger.scala:49)
scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:205)
scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:146)
sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3(ForkedJava.scala:55)
sbt.internal.inc.javac.ForkedJava$.$anonfun$launch$3$adapted(ForkedJava.scala:48)
sbt.internal.inc.javac.ForkedJava$.$anonfun$withArgumentFile$1(ForkedJava.scala:77)
sbt.io.IO$.withTemporaryDirectory(IO.scala:490)
sbt.io.IO$.withTemporaryDirectory(IO.scala:500)
sbt.internal.inc.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:74)
sbt.internal.inc.javac.ForkedJava$.launch(ForkedJava.scala:48)
sbt.internal.inc.javac.ForkedJavaCompiler.run(ForkedJava.scala:103)
sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$12(AnalyzingJavaCompiler.scala:167)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:251)
sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:156)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:98)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:191)
sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:179)
scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:356)
scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:113)
scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:88)
scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:308)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by cerveada** [comment] 2022-04-08 11:51
This does not look like a Spline issue, more like some kind of Java configuration problem.
The compilation works fine on my machine as well as in our integration environment.

I would check that the paths in the error are correct. Also, that right jdk is on path and JAVA_HOME is set correctly.
If all of that is good, you may try to update the jdk or maybe maven.

**Closed as completed** 2022-05-19 11:54 UTC
Labels: invalid
