### ISSUE TITLE
Need to deploy on Synapse environment in order to track lineage for Synapse notebooks

### ISSUE THREAD

**Issue by talhagithub02** [AbsaOSS/spline-spark-agent#777] opened 2023-12-15 10:45 UTC
First, thank you for a wonderful library, 

I have a requirement where I would need to scan pyspark notebook but within Azure synapse environment so whenever we run a synapse notebook the lineage for it gets tracked by spline, I am not sure how to achieve this, I have tested spline on local pyspark scripts which is good to go but what and where to deploy on synapse environment is confusing.

Your assistance required and your time is appreciated.

Thanks,
Talha

**Comment by wajda** [comment] 2023-12-22 18:14
Duplicate of #778

**Closed as not planned by wajda** 2023-12-22 18:14 UTC
Labels: duplicate
