### ISSUE TITLE
SparkListener in Spark on YARN does not work

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline-spark-agent#199] opened 2021-04-09 09:25 UTC
We need to investigate how to enable SparkListener in Spark on YARN.

This makes the spark agent not work in codeless mode on the cluster.

**Comment by wajda** [comment] 2021-04-09 09:45
For the reference:

The issue #102 confirms that Spline on YARN works for some users. (The fact the user gets that error means that Spline is in action already)

On the other hand other users out there complain about Spark query listeners in general aren't called on their YARN
https://stackoverflow.com/questions/48822020/custom-queryexecutionlistener-not-being-called

**Comment by wajda** [comment] 2021-10-20 11:06
It doesn't seem to occur from the comments we receive from the community. Taking into account that the issue was only reported against Spline+YARN combination I conclude that it's either caused by improper usage of YARN or a bug in certain YARN versions that was fixed later. Thus I'm closing the issue as "cannot reproduce"

**Closed as completed by wajda** 2021-10-20 11:06 UTC
Labels: invalid
